import { OccasionDefinition, OccasionId, CulturalSphere, SceneDefinition, LanguageInfo, Language, CulturalSphereInfo } from '../types';

export const GLOBAL_NEGATIVE_PROMPT =
  'text, watermark, signature, letters, numbers, font, typography, logo, blurry, distorted, low resolution, deformed, bad anatomy, ugly, artifacts, cartoonish, oversaturated, pixelated, cluttered composition, busy center';

export const CULTURAL_SPHERES: Record<CulturalSphere, CulturalSphereInfo> = {
  global: {
    id: 'global',
    label: 'Global & Worldwide',
    flag: '🌐',
    description: 'Universal modern aesthetics, English & Spanish greetings',
    defaultLanguage: 'en',
    languages: ['en', 'es', 'fr', 'de', 'it'],
  },
  south_asia: {
    id: 'south_asia',
    label: 'India & South Asia',
    flag: '🇮🇳',
    description: 'Festivals, Krishna, Chai, Diyas, Devanagari & Indic scripts',
    defaultLanguage: 'hi',
    languages: ['hi', 'mr', 'gu', 'pa', 'te', 'ta', 'bn', 'en', 'hinglish'],
  },
  latin_america: {
    id: 'latin_america',
    label: 'Latin America & Iberia',
    flag: '💃',
    description: 'Vibrant tropical scenes, fiesta, sunflowers, Español & Português',
    defaultLanguage: 'es',
    languages: ['es', 'pt', 'en'],
  },
  middle_east: {
    id: 'middle_east',
    label: 'Middle East & Arab World',
    flag: '🕌',
    description: 'Arabian Dallah, Crescent Moon, Fanous, Arabic RTL calligraphy',
    defaultLanguage: 'ar',
    languages: ['ar', 'tr', 'en', 'fr'],
  },
  east_asia: {
    id: 'east_asia',
    label: 'East & Southeast Asia',
    flag: '🌸',
    description: 'Mount Fuji, Cherry Blossoms, Zen gardens, Japanese, Korean & Chinese',
    defaultLanguage: 'ja',
    languages: ['ja', 'ko', 'zh', 'id', 'en'],
  },
  europe: {
    id: 'europe',
    label: 'Europe & UK',
    flag: '🏰',
    description: 'Parisian cafés, Swiss Alps, Tuscan sunsets, French, German & Italian',
    defaultLanguage: 'fr',
    languages: ['fr', 'de', 'it', 'en', 'es'],
  },
  africa: {
    id: 'africa',
    label: 'Africa & Safari',
    flag: '🌍',
    description: 'Serengeti sunrise, Kilimanjaro, African warmth, Swahili & English',
    defaultLanguage: 'en',
    languages: ['en', 'sw', 'fr'],
  },
};

export const ALL_LANGUAGES: Record<Language, LanguageInfo> = {
  en: { id: 'en', label: 'English', nativeLabel: 'English', fontFamily: "'Cinzel', 'Playfair Display', serif" },
  es: { id: 'es', label: 'Spanish', nativeLabel: 'Español', fontFamily: "'Playfair Display', 'Cinzel', serif" },
  pt: { id: 'pt', label: 'Portuguese', nativeLabel: 'Português', fontFamily: "'Playfair Display', serif" },
  ar: { id: 'ar', label: 'Arabic', nativeLabel: 'العربية', fontFamily: "'Amiri', 'Cairo', serif", isRtl: true },
  tr: { id: 'tr', label: 'Turkish', nativeLabel: 'Türkçe', fontFamily: "'Playfair Display', serif" },
  ja: { id: 'ja', label: 'Japanese', nativeLabel: '日本語', fontFamily: "'Noto Serif JP', serif" },
  ko: { id: 'ko', label: 'Korean', nativeLabel: '한국어', fontFamily: "'Noto Serif KR', serif" },
  zh: { id: 'zh', label: 'Chinese', nativeLabel: '简体中文', fontFamily: "'Noto Serif SC', serif" },
  id: { id: 'id', label: 'Indonesian', nativeLabel: 'Bahasa Indonesia', fontFamily: "'Poppins', sans-serif" },
  fr: { id: 'fr', label: 'French', nativeLabel: 'Français', fontFamily: "'Playfair Display', 'Great Vibes', serif" },
  de: { id: 'de', label: 'German', nativeLabel: 'Deutsch', fontFamily: "'Playfair Display', serif" },
  it: { id: 'it', label: 'Italian', nativeLabel: 'Italiano', fontFamily: "'Playfair Display', serif" },
  sw: { id: 'sw', label: 'Swahili', nativeLabel: 'Kiswahili', fontFamily: "'Poppins', sans-serif" },
  hi: { id: 'hi', label: 'Hindi', nativeLabel: 'हिन्दी', fontFamily: "'Rozha One', 'Yatra One', sans-serif" },
  mr: { id: 'mr', label: 'Marathi', nativeLabel: 'मराठी', fontFamily: "'Rozha One', 'Yatra One', sans-serif" },
  gu: { id: 'gu', label: 'Gujarati', nativeLabel: 'ગુજરાતી', fontFamily: "'Anek Gujarati', 'Rasa', serif" },
  pa: { id: 'pa', label: 'Punjabi', nativeLabel: 'ਪੰਜਾਬੀ', fontFamily: "'Anek Gurmukhi', sans-serif" },
  te: { id: 'te', label: 'Telugu', nativeLabel: 'తెలుగు', fontFamily: "'Anek Telugu', sans-serif" },
  ta: { id: 'ta', label: 'Tamil', nativeLabel: 'தமிழ்', fontFamily: "'Anek Tamil', sans-serif" },
  bn: { id: 'bn', label: 'Bengali', nativeLabel: 'বাংলা', fontFamily: "'Anek Bangla', sans-serif" },
  hinglish: { id: 'hinglish', label: 'Hinglish', nativeLabel: 'Hinglish', fontFamily: "'Poppins', sans-serif" },
};

export const SCENES: Record<string, SceneDefinition> = {
  // --- Global / Anglosphere ---
  gm_sunrise: {
    id: 'gm_sunrise',
    label: 'Misty Mountain Sunrise',
    description: 'Golden sunbeams breaking through morning mist over serene peaks',
    icon: '🌅',
    previewImage: '/scenes/gm_sunrise.jpg',
    promptModifier:
      'cinematic golden hour sunrise, breathtaking sunbeams cutting through soft morning mist, tranquil mountain landscape, warm amber and gold atmospheric lighting, wide depth of field, 8k fine art photography, clean spacious central area for typography',
    sphere: 'all',
    colorPalette: {
      primary: '#FFE259',
      secondary: '#FFA751',
      accent: '#FF7043',
      goldGradient: ['#FFF275', '#FFA751', '#E5A638'],
      scrimOverlay: 'rgba(15, 8, 4, 0.42)',
      textColor: '#FFFFFF',
    },
  },
  bday_cake: {
    id: 'bday_cake',
    label: 'Gourmet Birthday Cake',
    description: 'Artisan luxury birthday cake with glowing warm golden candles',
    icon: '🎂',
    previewImage: '/scenes/bday_cake.jpg',
    promptModifier:
      'gourmet luxury multi-tier celebration birthday cake with glowing warm golden candles, exquisite chocolate and gold foil decorations, dark velvet celebration backdrop, champagne sparkles bokeh, 50mm f/1.8 studio photography',
    sphere: 'all',
    colorPalette: {
      primary: '#FFD700',
      secondary: '#FFA000',
      accent: '#FF6F00',
      goldGradient: ['#FFFDE7', '#FFD54F', '#FF8F00'],
      scrimOverlay: 'rgba(20, 8, 4, 0.52)',
      textColor: '#FFFFFF',
    },
  },
  mot_climber: {
    id: 'mot_climber',
    label: 'Summit Climber at Dawn',
    description: 'Triumphant climber on mountain peak illuminated by rising sunbeams',
    icon: '🧗',
    previewImage: '/scenes/mot_climber.jpg',
    promptModifier:
      'triumphant silhouette of an explorer/climber standing atop a dramatic mountain summit at sunrise, magnificent golden volumetric sunbeams breaking through clouds, breathtaking vast horizon, inspirational epic photography',
    sphere: 'all',
    colorPalette: {
      primary: '#FFE259',
      secondary: '#FFA751',
      accent: '#FF7043',
      goldGradient: ['#FFF9C4', '#FFA751', '#E65100'],
      scrimOverlay: 'rgba(12, 10, 8, 0.45)',
      textColor: '#FFFFFF',
    },
  },

  // --- Latin America & Iberia ---
  lat_sunflower: {
    id: 'lat_sunflower',
    label: 'Andean Sunflowers Sunrise',
    description: 'Vibrant golden sunflowers bathed in warm tropical morning sun',
    icon: '🌻',
    previewImage: '/scenes/lat_sunflower.jpg',
    promptModifier:
      'gorgeous field of blooming golden sunflowers reaching toward a radiant tropical sunrise, blue mountain silhouette in background, warm amber and gold light, 8k nature photography',
    sphere: 'latin_america',
    colorPalette: {
      primary: '#FFD54F',
      secondary: '#FFA000',
      accent: '#FF6F00',
      goldGradient: ['#FFF9C4', '#FFD54F', '#FF8F00'],
      scrimOverlay: 'rgba(18, 12, 4, 0.45)',
      textColor: '#FFFFFF',
    },
  },

  // --- Middle East & Arab World ---
  me_crescent: {
    id: 'me_crescent',
    label: 'Golden Crescent & Mosque',
    description: 'Glowing golden crescent moon over majestic silhouetted arches',
    icon: '🌙',
    previewImage: '/scenes/me_crescent.jpg',
    promptModifier:
      'magical twilight night with glowing golden crescent moon floating in deep indigo sky above a silhouetted Arabian mosque skyline, sparkling stars, sacred serene Islamic aesthetics, 8k fine art',
    sphere: 'middle_east',
    colorPalette: {
      primary: '#FFD700',
      secondary: '#90CAF9',
      accent: '#FFC107',
      goldGradient: ['#FFF8E1', '#FFD54F', '#FF8F00'],
      scrimOverlay: 'rgba(8, 12, 28, 0.55)',
      textColor: '#FFFFFF',
    },
  },
  me_dallah: {
    id: 'me_dallah',
    label: 'Arabian Dallah & Dates',
    description: 'Traditional golden brass Dallah coffee pot with royal Medjool dates',
    icon: '🫖',
    previewImage: '/scenes/me_dallah.jpg',
    promptModifier:
      'luxurious authentic ornate golden brass Arabian Dallah coffee pot with fine porcelain finjan cup and bowl of Medjool dates on rich velvet carpet, warm golden hour ambient lighting, 8k photography',
    sphere: 'middle_east',
    colorPalette: {
      primary: '#FFD700',
      secondary: '#FFA000',
      accent: '#D7CCC8',
      goldGradient: ['#FFFDE7', '#FFD54F', '#FF8F00'],
      scrimOverlay: 'rgba(22, 14, 6, 0.52)',
      textColor: '#FFFFFF',
    },
  },

  // --- East & Southeast Asia ---
  ea_fuji: {
    id: 'ea_fuji',
    label: 'Mount Fuji & Cherry Blossoms',
    description: 'Snow-capped Mount Fuji framed by delicate pink sakura branches at dawn',
    icon: '🗻',
    previewImage: '/scenes/ea_fuji.jpg',
    promptModifier:
      'iconic majestic snow-capped Mount Fuji framed by blooming pink cherry blossom sakura branches during soft morning dawn, pastel pink and blue sky, serene lake reflection, 8k masterwork Japanese landscape photography',
    sphere: 'east_asia',
    colorPalette: {
      primary: '#F8BBD0',
      secondary: '#90CAF9',
      accent: '#FFD54F',
      goldGradient: ['#FCE4EC', '#F8BBD0', '#D81B60'],
      scrimOverlay: 'rgba(12, 14, 24, 0.45)',
      textColor: '#FFFFFF',
    },
  },

  // --- Europe ---
  eu_paris: {
    id: 'eu_paris',
    label: 'Parisian Café & Croissant',
    description: 'Chic Parisian café table with fresh buttery croissant and espresso at sunrise',
    icon: '🥐',
    previewImage: '/scenes/eu_paris.jpg',
    promptModifier:
      'chic Parisian café outdoor marble table with fresh golden flaky croissant and artisan coffee in porcelain cup, soft golden morning light on cobblestone street with blooming lavender, 8k lifestyle photography',
    sphere: 'europe',
    colorPalette: {
      primary: '#FFE082',
      secondary: '#D7CCC8',
      accent: '#BCAAA4',
      goldGradient: ['#FFF8E1', '#FFE082', '#A1887F'],
      scrimOverlay: 'rgba(20, 14, 10, 0.45)',
      textColor: '#FFFFFF',
    },
  },

  // --- Africa & Safari ---
  af_serengeti: {
    id: 'af_serengeti',
    label: 'Serengeti Acacia Sunrise',
    description: 'Iconic acacia tree silhouetted against a magnificent golden savanna sunrise',
    icon: '🦁',
    previewImage: '/scenes/af_serengeti.jpg',
    promptModifier:
      'majestic silhouette of an iconic African flat-top acacia tree against a breathtaking glowing orange and golden savanna sunrise in the Serengeti, vast peaceful wilderness, 8k wildlife photography',
    sphere: 'africa',
    colorPalette: {
      primary: '#FFA726',
      secondary: '#FF7043',
      accent: '#FFD54F',
      goldGradient: ['#FFF3E0', '#FFA726', '#D84315'],
      scrimOverlay: 'rgba(24, 10, 4, 0.50)',
      textColor: '#FFFFFF',
    },
  },

  // --- South Asia ---
  gm_krishna: {
    id: 'gm_krishna',
    label: 'Shri Krishna Darshan',
    description: 'Lord Krishna with divine golden flute and vibrant peacock feather (Mor Pankh)',
    icon: '🦚',
    previewImage: '/scenes/gm_krishna.jpg',
    promptModifier:
      'divine Lord Shri Krishna celestial silhouette with golden bansuri flute and iridescent peacock feather mor pankh, ethereal sacred golden morning aura, soft holy temple mist in Vrindavan, devotional sacred lighting, magnificent 8k fine art',
    sphere: 'south_asia',
    colorPalette: {
      primary: '#80DEEA',
      secondary: '#FFD54F',
      accent: '#FFCA28',
      goldGradient: ['#E0F7FA', '#FFD54F', '#FF8F00'],
      scrimOverlay: 'rgba(6, 18, 28, 0.52)',
      textColor: '#FFFFFF',
    },
  },
  fest_diyas: {
    id: 'fest_diyas',
    label: 'Glowing Brass Diyas & Rangoli',
    description: 'Traditional Indian brass oil lamps with warm flames and fresh marigold rangoli',
    icon: '🪔',
    previewImage: '/scenes/fest_diyas.jpg',
    promptModifier:
      'traditional glowing brass diya oil lamps with soft dancing warm flames, fresh orange and yellow marigold flower rangoli, dark royal velvet festive background, warm festive bokeh, rich Indian Diwali elegance, cinematic 8k render',
    sphere: 'south_asia',
    colorPalette: {
      primary: '#FFA000',
      secondary: '#FF6F00',
      accent: '#FFD700',
      goldGradient: ['#FFF8E1', '#FFD54F', '#FF8F00'],
      scrimOverlay: 'rgba(25, 8, 2, 0.55)',
      textColor: '#FFFFFF',
    },
  },
  gm_chai: {
    id: 'gm_chai',
    label: 'Desi Morning Chai',
    description: 'Steaming ginger cardamom tea in traditional clay kulhad cup at dawn',
    icon: '🫖',
    previewImage: '/scenes/gm_chai.jpg',
    promptModifier:
      'authentic Indian steaming masala chai tea in traditional terracotta clay kulhad cup on rustic wooden veranda, gentle morning golden hour dawn light, fresh green mint leaves, nostalgic warm morning aesthetic, cinematic 8k photography',
    sphere: 'south_asia',
    colorPalette: {
      primary: '#FFCC80',
      secondary: '#D7CCC8',
      accent: '#FFA726',
      goldGradient: ['#FFF3E0', '#FFB74D', '#F57C00'],
      scrimOverlay: 'rgba(28, 14, 8, 0.48)',
      textColor: '#FFFFFF',
    },
  },

  // --- Ganesh Chaturthi Multi-Scenes ---
  ganesha_royal: {
    id: 'ganesha_royal',
    label: 'Royal Darshan',
    description: 'Lalbaugcha Raja grand Lord Ganesha idol with majestic crown',
    icon: '👑',
    previewImage: '/scenes/ganesha_royal.jpg',
    promptModifier: 'Lalbaugcha Raja grand Lord Ganesha idol, majestic golden crown, opulent red velvet backdrop, temple flowers garland',
    sphere: 'south_asia',
    colorPalette: {
      primary: '#FFD700',
      secondary: '#FF8F00',
      accent: '#D32F2F',
      goldGradient: ['#FFFDE7', '#FFD54F', '#C62828'],
      scrimOverlay: 'rgba(25, 4, 4, 0.55)',
      textColor: '#FFFFFF',
    },
  },
  ganesha_gold: {
    id: 'ganesha_gold',
    label: 'Golden Bappa',
    description: 'Radiant golden Ganesha with glowing temple oil lamps',
    icon: '🪔',
    previewImage: '/scenes/ganesha_gold.jpg',
    promptModifier: 'glowing brass golden Lord Ganesha idol, warm flickering temple oil lamps, red hibiscus flowers',
    sphere: 'south_asia',
    colorPalette: {
      primary: '#FFE082',
      secondary: '#FFB300',
      accent: '#FF6F00',
      goldGradient: ['#FFF8E1', '#FFD54F', '#FF6F00'],
      scrimOverlay: 'rgba(20, 10, 4, 0.52)',
      textColor: '#FFFFFF',
    },
  },
  ganesha_modak: {
    id: 'ganesha_modak',
    label: 'Clay & Modak',
    description: 'Eco-friendly clay Ganpati with fresh marigolds & steamed modaks',
    icon: '🌺',
    previewImage: '/scenes/ganesha_modak.jpg',
    promptModifier: 'eco friendly clay Ganpati Bappa with fresh yellow orange marigold garland, sacred durva grass, silver plate of modaks',
    sphere: 'south_asia',
    colorPalette: {
      primary: '#FFCA28',
      secondary: '#66BB6A',
      accent: '#FF7043',
      goldGradient: ['#FFF9C4', '#FFD54F', '#388E3C'],
      scrimOverlay: 'rgba(16, 20, 10, 0.50)',
      textColor: '#FFFFFF',
    },
  },
  ganesha_temple: {
    id: 'ganesha_temple',
    label: 'Temple Aarti',
    description: 'Siddhivinayak morning aarti with sanctum sanctorum bells',
    icon: '🛕',
    previewImage: '/scenes/ganesha_temple.jpg',
    promptModifier: 'sacred Hindu temple sanctum sanctorum, morning aarti with brass bells, incense smoke, divine Ganesha murti',
    sphere: 'south_asia',
    colorPalette: {
      primary: '#FFD54F',
      secondary: '#FF8F00',
      accent: '#FFA000',
      goldGradient: ['#FFF8E1', '#FFCA28', '#E65100'],
      scrimOverlay: 'rgba(24, 12, 4, 0.55)',
      textColor: '#FFFFFF',
    },
  },

  // --- Diwali Multi-Scenes ---
  diwali_palace: {
    id: 'diwali_palace',
    label: 'Palace Courtyard',
    description: 'Grand royal palace courtyard illuminated with thousands of diyas',
    icon: '🏰',
    previewImage: '/scenes/diwali_palace.jpg',
    promptModifier: 'grand royal Indian palace courtyard during Diwali Deepotsav, illuminated by thousands of golden oil lamps',
    sphere: 'south_asia',
    colorPalette: {
      primary: '#FFE082',
      secondary: '#FF8F00',
      accent: '#FF6F00',
      goldGradient: ['#FFF8E1', '#FFD54F', '#FF6F00'],
      scrimOverlay: 'rgba(25, 10, 4, 0.52)',
      textColor: '#FFFFFF',
    },
  },
  diwali_diyas: {
    id: 'diwali_diyas',
    label: 'Brass Diyas',
    description: 'Rows of traditional terracotta & brass diyas with marigolds',
    icon: '🪔',
    previewImage: '/scenes/diwali_diyas.jpg',
    promptModifier: 'rows of traditional terracotta brass diyas with flickering golden flames, fresh orange marigold garlands',
    sphere: 'south_asia',
    colorPalette: {
      primary: '#FFA000',
      secondary: '#FF6F00',
      accent: '#FFD700',
      goldGradient: ['#FFF8E1', '#FFD54F', '#FF8F00'],
      scrimOverlay: 'rgba(28, 8, 2, 0.55)',
      textColor: '#FFFFFF',
    },
  },
  diwali_rangoli: {
    id: 'diwali_rangoli',
    label: 'Peacock Rangoli',
    description: 'Vibrant peacock floral rangoli with floating candle bowls',
    icon: '🌸',
    previewImage: '/scenes/diwali_rangoli.jpg',
    promptModifier: 'vibrant peacock floral rangoli on marble floor, surrounded by glowing floating diya bowls',
    sphere: 'south_asia',
    colorPalette: {
      primary: '#80DEEA',
      secondary: '#FF4081',
      accent: '#FFD700',
      goldGradient: ['#E0F7FA', '#FF80AB', '#FFD54F'],
      scrimOverlay: 'rgba(16, 6, 24, 0.52)',
      textColor: '#FFFFFF',
    },
  },
  diwali_lakshmi: {
    id: 'diwali_lakshmi',
    label: 'Lakshmi Blessings',
    description: 'Maa Lakshmi & Lord Ganesha divine blessings on golden lotus',
    icon: '✨',
    previewImage: '/scenes/diwali_lakshmi.jpg',
    promptModifier: 'Goddess Lakshmi and Lord Ganesha divine golden blessings, lotus flower throne, falling gold coins',
    sphere: 'south_asia',
    colorPalette: {
      primary: '#FFD700',
      secondary: '#FF4081',
      accent: '#FF8F00',
      goldGradient: ['#FFFDE7', '#FF80AB', '#FF6F00'],
      scrimOverlay: 'rgba(22, 6, 12, 0.55)',
      textColor: '#FFFFFF',
    },
  },

  // --- Navratri & Durga Puja ---
  durga_divine: {
    id: 'durga_divine',
    label: 'Maa Durga',
    description: 'Maa Durga radiant golden aura with divine trishul & lotus',
    icon: '🦁',
    previewImage: '/scenes/durga_divine.jpg',
    promptModifier: 'Maa Durga radiant divine aura, golden ornaments, holding trishul, lion mount, lotus flowers',
    sphere: 'south_asia',
    colorPalette: {
      primary: '#FF5252',
      secondary: '#FFD700',
      accent: '#FF9100',
      goldGradient: ['#FFEBEE', '#FFD700', '#D50000'],
      scrimOverlay: 'rgba(30, 4, 4, 0.55)',
      textColor: '#FFFFFF',
    },
  },
  navratri_garba: {
    id: 'navratri_garba',
    label: 'Garba Night',
    description: 'Vibrant traditional Garba Dandiya celebration with fairy lights',
    icon: '💃',
    previewImage: '/scenes/navratri_garba.jpg',
    promptModifier: 'traditional vibrant Garba Dandiya Raas celebration night, festive ethnic attire, bokeh fairy lights',
    sphere: 'south_asia',
    colorPalette: {
      primary: '#E040FB',
      secondary: '#FFD700',
      accent: '#00E676',
      goldGradient: ['#F3E5F5', '#FFD54F', '#AA00FF'],
      scrimOverlay: 'rgba(20, 4, 28, 0.52)',
      textColor: '#FFFFFF',
    },
  },

  // --- New Year 2026 ---
  newyear_fireworks: {
    id: 'newyear_fireworks',
    label: 'Fireworks',
    description: 'Spectacular midnight golden fireworks over modern skyline',
    icon: '🎆',
    previewImage: '/scenes/newyear_fireworks.jpg',
    promptModifier: 'spectacular midnight golden fireworks over modern city skyline',
    sphere: 'all',
    colorPalette: {
      primary: '#FFE082',
      secondary: '#80D8FF',
      accent: '#FF80AB',
      goldGradient: ['#FFF8E1', '#FFD54F', '#0091EA'],
      scrimOverlay: 'rgba(8, 12, 28, 0.55)',
      textColor: '#FFFFFF',
    },
  },
  newyear_gold: {
    id: 'newyear_gold',
    label: 'Sparkles',
    description: 'Festive champagne flutes with golden confetti & bokeh',
    icon: '🥂',
    previewImage: '/scenes/newyear_gold.jpg',
    promptModifier: 'luxury festive champagne flutes, golden confetti, sparkling bokeh lights',
    sphere: 'all',
    colorPalette: {
      primary: '#FFD700',
      secondary: '#FFA000',
      accent: '#FFE082',
      goldGradient: ['#FFFDE7', '#FFD54F', '#FF8F00'],
      scrimOverlay: 'rgba(20, 14, 4, 0.52)',
      textColor: '#FFFFFF',
    },
  },
};

export const OCCASIONS: Record<OccasionId, OccasionDefinition> = {
  ganesh_chaturthi: {
    id: 'ganesh_chaturthi',
    label: 'Ganesh Chaturthi',
    icon: '🐘',
    category: 'festival',
    defaultTitle: {
      mr: 'गणेशोत्सवाच्या हार्दिक शुभेच्छा',
      hi: 'गणेश चतुर्थी की हार्दिक शुभकामनाएं',
      gu: 'ગણેશ ચતુર્થીની હાર્દિક શુભેચ્છાઓ',
      pa: 'ਗਣੇਸ਼ ਚਤੁਰਥੀ ਦੀਆਂ ਮੁਬਾਰਕਾਂ',
      te: 'వినాయక చవితి శుభాకాంక్షలు',
      ta: 'விநாயகர் சதுர்த்தி நல்வாழ்த்துகள்',
      bn: 'গণেশ চতুর্থীর শুভেচ্ছা',
      en: 'Happy Ganesh Chaturthi',
      es: '¡Feliz Ganesh Chaturthi!',
    },
    scenes: [
      SCENES.ganesha_royal,
      SCENES.ganesha_gold,
      SCENES.ganesha_modak,
      SCENES.ganesha_temple,
    ],
    sampleQuotes: {
      mr: ['वक्रतुंड महाकाय सूर्यकोटि समप्रभ। निर्विघ्नं कुरु मे देव सर्वकार्येषु सर्वदा॥ बाप्पाच्या आगमनाने आपल्या घरात सुख, समृद्धी आणि समाधान लाभो! गणपती बाप्पा मोरया!'],
      hi: ['भगवान श्री गणेश आपके जीवन के सभी विघ्नों को हरें और सुख, शांति व समृद्धि का वरदान दें। गणपति बाप्पा मोरया!'],
      gu: ['ભગવાન શ્રી ગણેશ તમારા જીવનમાં સુખ, શાંતિ અને સમૃદ્ધિ લાવે. ગણેશ ચતુર્થીની હાર્દિક શુભકામનાઓ!'],
      pa: ['ਗਣਪਤੀ ਬੱਪਾ ਤੁਹਾਡੀ ਝੋਲੀ ਖੁਸ਼ੀਆਂ ਨਾਲ ਭਰ ਦੇਣ। ਗਣੇਸ਼ ਚਤੁਰਥੀ ਦੀਆਂ ਮੁਬਾਰਕਾਂ!'],
      te: ['వినాయక చవితి పర్వదినం సందర్భంగా మీకు, మీ కుటుంబ సభ్యులకు హృదయపూర్వక శుభాకాంక్షలు!'],
      ta: ['விநாயகர் சதுர்த்தி நன்னாளில் உங்கள் வாழ்வில் எல்லா வளமும் நலமும் பொங்கட்டும்!'],
      bn: ['ভগবান শ্রী গণেশের আশীর্বাদে আপনার জীবন সুখ, শান্তি ও সমৃদ্ধিতে ভরে উঠুক।'],
      en: ['May Lord Ganesha remove all obstacles from your path and bless your home with peace, happiness, and prosperity! Ganpati Bappa Morya!'],
      es: ['¡Que el Señor Ganesha elimine todos los obstáculos de tu camino y bendiga tu hogar con paz, salud y alegría!'],
    },
    recipientSuggestions: [
      { label: 'Family', en: 'Beloved Family', native: 'परिवार / कुटुंब' },
      { label: 'Friend', en: 'Dear Friend', native: 'मित्र / दोस्त' },
      { label: 'All', en: 'All Devotees', native: 'सर्व गणेशभक्त' },
    ],
  },
  diwali: {
    id: 'diwali',
    label: 'Diwali & Deepotsav',
    icon: '🪔',
    category: 'festival',
    defaultTitle: {
      mr: 'शुभ दीपावली',
      hi: 'दीपावली की शुभकामनाएं',
      gu: 'દિવાળીની શુભકામનાઓ',
      pa: 'ਦਿਵਾਲੀ ਮੁਬਾਰਕ',
      te: 'దీపావళి శుభాకాంక్షలు',
      ta: 'தீபாவளி நல்வாழ்த்துகள்',
      bn: 'শুভ দীপাবলি',
      en: 'Happy & Prosperous Diwali',
      es: '¡Feliz Diwali!',
    },
    scenes: [
      SCENES.diwali_palace,
      SCENES.diwali_diyas,
      SCENES.diwali_rangoli,
      SCENES.diwali_lakshmi,
    ],
    sampleQuotes: {
      mr: ['दिव्यांचा हा तेजोमय सण आपल्या आयुष्यातील अंधार दूर करून सुख, समृद्धी आणि यशाचा प्रकाश घेऊन येवो. शुभ दीपावली!'],
      hi: ['दीपों का यह पावन पर्व आपके जीवन को प्रकाश, आनंद, उत्तम स्वास्थ्य और अपार वैभव से भर दे। शुभ दीपावली!'],
      gu: ['દિવાળીના શુભ પર્વ પર આપના જીવનમાં સુખ, શાંતિ અને સમૃદ્ધિનો દીપક સદાય પ્રજ્વલિત રહે.'],
      en: ['May the divine glow of Diwali lamps illuminate your path with joy, good health, and boundless prosperity! Happy Diwali!'],
    },
    recipientSuggestions: [
      { label: 'Family', en: 'Beloved Family', native: 'प्रिय परिवार' },
      { label: 'Friends', en: 'Dear Friends', native: 'सर्व मित्रमंडळी' },
    ],
  },
  navratri: {
    id: 'navratri',
    label: 'Navratri & Durga',
    icon: '🌸',
    category: 'festival',
    defaultTitle: {
      mr: 'नवरात्रीच्या हार्दिक शुभेच्छा',
      hi: 'शुभ नवरात्रि व दुर्गा पूजा',
      gu: 'નવરાત્રીની હાર્દિક શુભેચ્છાઓ',
      bn: 'শুভ দুর্গাপূজা',
      en: 'Happy Navratri & Durga Puja',
    },
    scenes: [
      SCENES.durga_divine,
      SCENES.navratri_garba,
    ],
    sampleQuotes: {
      mr: ['आई दुर्गेच्या आशीर्वादाने आपल्या आयुष्यात सामर्थ्य, आनंद आणि भरभराट लाभो. नवरात्रोत्सवाच्या मनःपूर्वक शुभेच्छा!'],
      hi: ['माँ दुर्गा आपको शक्ति, बुद्धि, आरोग्य और सुख-समृद्धि प्रदान करें। शुभ नवरात्रि!'],
      gu: ['માં આદ્યશક્તિ આપની તમામ મનોકામનાઓ પૂર્ણ કરે. નવરાત્રી પર્વની હાર્દિક શુભેચ્છાઓ!'],
      en: ['May Goddess Durga bestow strength, joy, harmony, and prosperity upon you and your family! Happy Navratri!'],
    },
    recipientSuggestions: [
      { label: 'Family', en: 'Family & Friends', native: 'सर्व प्रियजन' },
    ],
  },
  new_year: {
    id: 'new_year',
    label: 'New Year 2026',
    icon: '🎆',
    category: 'celebration',
    defaultTitle: {
      en: 'Happy New Year 2026!',
      es: '¡Feliz Año Nuevo 2026!',
      fr: 'Bonne Année 2026 !',
      hi: 'नव वर्ष 2026 की शुभकामनाएं',
      mr: 'नवीन वर्षाच्या हार्दिक शुभेच्छा 2026',
    },
    scenes: [
      SCENES.newyear_fireworks,
      SCENES.newyear_gold,
    ],
    sampleQuotes: {
      en: ['Wishing you 365 days of grand success, sparkling laughter, great health, and boundless joy in 2026!'],
      hi: ['आने वाला नया साल आपके जीवन में नई उमंग, खुशियां और अपार सफलताएं लेकर आए। नव वर्ष 2026 मंगलमय हो!'],
      mr: ['नवीन वर्ष २०२६ आपणास सुख, समृद्धी, आरोग्य आणि भरभराटीचे जावो. नवीन वर्षाच्या हार्दिक शुभेच्छा!'],
    },
    recipientSuggestions: [
      { label: 'Everyone', en: 'All Loved Ones', native: 'सर्व आप्तस्वकीय' },
    ],
  },

  good_morning: {
    id: 'good_morning',
    label: 'Good Morning',
    icon: '☀️',
    category: 'daily',
    defaultTitle: {
      en: 'Good Morning',
      es: '¡Buenos Días!',
      pt: 'Bom Dia!',
      ar: 'صباح الخير',
      tr: 'Günaydın',
      ja: 'おはようございます',
      ko: '좋은 아침입니다',
      zh: '早安',
      id: 'Selamat Pagi',
      fr: 'Bonjour !',
      de: 'Guten Morgen',
      it: 'Buongiorno !',
      sw: 'Habari ya Asubuhi',
      hi: 'शुभ प्रभात',
      mr: 'शुभ प्रभात',
      gu: 'શુભ સવાર',
      pa: 'ਸ਼ੁਭ ਸਵੇਰ',
      te: 'శుభోదయం',
      ta: 'காலை வணக்கம்',
      bn: 'শুভ সকাল',
      hinglish: 'Shubh Prabhat',
    },
    scenes: [
      SCENES.gm_sunrise,
      SCENES.gm_krishna,
      SCENES.ea_fuji,
      SCENES.lat_sunflower,
      SCENES.me_dallah,
      SCENES.eu_paris,
      SCENES.af_serengeti,
      SCENES.gm_chai,
    ],
    sampleQuotes: {
      en: [
        'May the morning sunshine bring peace to your mind, warmth to your heart, and boundless joy to your day.',
        'Every sunrise is an invitation to brighten someone’s life. Wishing you a blessed and wonderful day!',
      ],
      es: [
        'Que los primeros rayos de la mañana traigan paz a tu mente, salud y alegría infinita a tu día. ¡Buenos días!',
        'Que Dios bendiga tu día con amor, éxito y momentos felices.',
      ],
      pt: [
        'Que o seu dia seja repleto de paz, luz e muitas bênçãos. Tenha um excelente e produtivo dia!',
      ],
      ar: [
        'صباح الخير والبركة! أتمنى لك يوماً جميلاً مليئاً بالصحة والراحة والسرور.',
        'اللهم اجعل هذا الصباح بداية لكل خير وتيسير لكل أمر.',
      ],
      tr: [
        'Gününüz aydın, neşeniz bol, dualarınız kabul olsun. Harika bir gün dilerim!',
      ],
      ja: [
        'おはようございます！今日も笑顔溢れる素晴らしい一日になりますように。',
      ],
      ko: [
        '좋은 아침입니다! 오늘 하루도 건강과 행복이 가득하시기를 바랍니다.',
      ],
      zh: [
        '早安！愿清晨的第一缕阳光带给您健康、平安与喜悦，祝您度过美好的一天。',
      ],
      id: [
        'Selamat pagi! Semoga hari ini membawakan kedamaian, kesehatan dan kebahagiaan untukmu.',
      ],
      fr: [
        'Bonjour ! Que cette nouvelle journée vous apporte sérénité, joie et pleine réussite.',
      ],
      de: [
        'Guten Morgen! Möge dein Tag voller positiver Energie, Freude und Erfolg sein.',
      ],
      it: [
        'Buongiorno! Ti auguro una splendida giornata piena di luce, serenità e sorrisi.',
      ],
      sw: [
        'Habari ya asubuhi! Siku yako iwe yenye amani tele, afya njema na mafanikio mema.',
      ],
      hi: [
        'सवेरे की पहली किरण आपके जीवन में नई उमंग, उत्साह और अपार खुशियां लेकर आए। आपका दिन मंगलमय हो।',
      ],
      mr: [
        'सूर्याची पहिली किरण आपल्या आयुष्यात सुख, समृद्धी, शांती आणि उत्तम आरोग्य घेऊन येवो. शुभ प्रभात!',
      ],
      gu: [
        'સવારનું પહેલું કિરણ તમારા જીવનમાં નવી ખુશીઓ અને ઉમંગ લઈને આવે. શુભ સવાર! જય શ્રી કૃષ્ણ.',
      ],
      pa: [
        'ਵਾਹਿਗੁਰੂ ਜੀ ਦੀ ਕਿਰਪਾ ਨਾਲ ਤੁਹਾਡਾ ਅੱਜ ਦਾ ਦਿਨ ਖੁਸ਼ੀਆਂ ਅਤੇ ਤਰੱਕੀ ਨਾਲ ਭਰਿਆ ਰਹੇ। ਸ਼ੁਭ ਸਵੇਰ!',
      ],
      te: [
        'ఈ ఉదయపు తొలి కిరణాలు మీ జీవితంలో సరికొత్త ఉత్సాహాన్ని నింపాలని కోరుకుంటూ... శుభోదయం!',
      ],
      ta: [
        'இனிய காலை வணக்கம்! உங்கள் இன்றைய நாள் மகிழ்ச்சியும் அமைதியும் நிறைந்ததாக அமையட்டும்.',
      ],
      bn: [
        'সকালের প্রথম আলো আপনার জীবনে নতুন আশা আর আনন্দ নিয়ে আসুক। শুভ সকাল!',
      ],
      hinglish: [
        'Aapka har din khushiyon aur nayi umang se bhara ho. Shubh Prabhat!',
      ],
    },
    recipientSuggestions: [
      { label: 'Family', en: 'Dearest Family', native: 'Familia / परिवार' },
      { label: 'Mom', en: 'Dearest Mom', native: 'Mom / माता जी' },
      { label: 'Dad', en: 'Respected Dad', native: 'Dad / पिता जी' },
      { label: 'Friend', en: 'Dear Friend', native: 'Friend / मित्र' },
      { label: 'Colleague', en: 'Dear Colleague', native: 'Colleague / साथी' },
    ],
  },
  birthday: {
    id: 'birthday',
    label: 'Happy Birthday',
    icon: '🎂',
    category: 'celebration',
    defaultTitle: {
      en: 'Happy Birthday',
      es: '¡Feliz Cumpleaños!',
      pt: 'Feliz Aniversário!',
      ar: 'عيد ميلاد سعيد',
      tr: 'İyi ki Doğdun!',
      ja: 'お誕生日おめでとう',
      ko: '생일 축하합니다',
      zh: '生日快乐',
      id: 'Selamat Ulang Tahun',
      fr: 'Joyeux Anniversaire !',
      de: 'Alles Gute zum Geburtstag!',
      it: 'Buon Compleanno !',
      sw: 'Heri ya Siku ya Kuzaliwa',
      hi: 'जन्मदिन की हार्दिक शुभकामनाएं',
      mr: 'वाढदिवसाच्या हार्दिक शुभेच्छा',
      gu: 'જન્મદિવસની હાર્દિક શુભેચ્છાઓ',
      pa: 'ਜਨਮਦਿਨ ਦੀਆਂ ਲੱਖ ਲੱਖ ਵਧਾਈਆਂ',
      te: 'జన్మదిన శుభాకాంక్షలు',
      ta: 'பிறந்தநாள் நல்வாழ்த்துகள்',
      bn: 'শুভ জন্মদিন',
      hinglish: 'Janamdin Mubarak',
    },
    scenes: [
      SCENES.bday_cake,
      SCENES.ea_fuji,
      SCENES.eu_paris,
    ],
    sampleQuotes: {
      en: [
        'Wishing you a year filled with grand adventures, immense laughter, good health, and boundless prosperity! Happy Birthday!',
      ],
      es: [
        '¡Que este nuevo año de vida esté lleno de infinitas bendiciones, salud, amor y mucha felicidad! ¡Feliz Cumpleaños!',
      ],
      pt: [
        'Parabéns! Que sua vida seja sempre abençoada com muita saúde, paz, amor e grandes conquistas.',
      ],
      ar: [
        'كل عام وأنت بألف خير وصحة وسعادة، أتمنى لك عاماً مليئاً بالنجاح وتحقيق الأمنيات.',
      ],
      tr: [
        'Yeni yaşının sana sağlık, mutluluk ve başarı getirmesini dilerim. Doğum günün kutlu olsun!',
      ],
      ja: [
        'お誕生日おめでとうございます！健康と幸福に満ちた素晴らしい一年になりますように。',
      ],
      ko: [
        '생신을 진심으로 축하드립니다! 늘 건강하시고 뜻하시는 모든 일이 이루어지길 기원합니다.',
      ],
      zh: [
        '祝您生日快乐！愿新的一年健康如意、福气满满、前程似锦。',
      ],
      fr: [
        'Joyeux Anniversaire ! Que cette nouvelle année vous comble de bonheur, de santé et de réussites.',
      ],
      de: [
        'Herzlichen Glückwunsch zum Geburtstag! Möge dein neues Lebensjahr voller Glück und Gesundheit sein.',
      ],
      it: [
        'Buon Compleanno! Ti auguro 365 giorni di felicità, salute e amore infinito.',
      ],
      sw: [
        'Heri ya siku ya kuzaliwa! Mwenyezi Mungu akujalie maisha marefu na baraka tele.',
      ],
      hi: [
        'ईश्वर आपको उत्तम स्वास्थ्य, दीर्घायु, सुख, समृद्धि और निरंतर सफलता प्रदान करे। जन्मदिन की हार्दिक शुभकामनाएं!',
      ],
      mr: [
        'ईश्वर आपणास दीर्घायुष्य, उत्तम आरोग्य आणि भरभराटीचे आयुष्य देवो. वाढदिवसाच्या मनःपूर्वक शुभेच्छा!',
      ],
      gu: [
        'ભગવાન તમને દીર્ઘાયુષ્ય, સારું સ્વાસ્થ્ય અને અખૂટ સુખ-સમૃદ્ધિ આપે. જન્મદિવસની શુભેચ્છાઓ!',
      ],
      pa: [
        'ਪਰਮਾਤਮਾ ਤੁਹਾਨੂੰ ਲੰਬੀ ਉਮਰ, ਚੰਗੀ ਸਿਹਤ ਅਤੇ ਹਰ ਖੇਤਰ ਵਿੱਚ ਕਾਮਯਾਬੀ ਬਖਸ਼ਣ। ਜਨਮਦਿਨ ਮੁਬਾਰਕ!',
      ],
      te: ['మీరు ఆయురారోగ్యాలతో, సకల ఐశ్వర్యాలతో కలకాలం వర్ధిల్లాలని మనసారా కోరుకుంటూ... జన్మదిన శుభాకాంక్షలు!'],
      ta: ['இனிய பிறந்தநாள் நல்வாழ்த்துகள்! இறைவன் உங்களுக்கு நீண்ட ஆயுளும் ஆரோக்கியமும் தந்தருளட்டும்.'],
      bn: ['ঈশ্বর আপনাকে দীর্ঘায়ু, সুস্বাস্থ্য ও অপার আনন্দ দান করুন। শুভ জন্মদিন!'],
      hinglish: ['Aapko janamdin ki dher saari shubhkaamnayein! May all your dreams come true.'],
    },
    recipientSuggestions: [
      { label: 'Friend', en: 'Dear Friend', native: 'Amigo / मित्र' },
      { label: 'Sister', en: 'Dearest Sister', native: 'Sister / बहना' },
      { label: 'Brother', en: 'Dear Brother', native: 'Brother / भाई' },
      { label: 'Partner', en: 'My Love', native: 'My Love / Amor' },
    ],
  },
  motivation: {
    id: 'motivation',
    label: 'Daily Motivation',
    icon: '⚡',
    category: 'mindset',
    defaultTitle: {
      en: 'Keep Rising',
      es: '¡Sigue Adelante!',
      pt: 'Força e Foco!',
      ar: 'واصل الصعود',
      tr: 'Asla Vazgeçme',
      ja: '限界を超えて',
      ko: '끝없는 도전',
      zh: '勇往直前',
      fr: 'Dépasse-toi !',
      de: 'Gib niemals auf',
      it: 'Vinci sempre',
      sw: 'Songa Mbele',
      hi: 'सफलता की राह',
      mr: 'यशस्वी भव',
      gu: 'સફળતાનો માર્ગ',
      pa: 'ਚੜ੍ਹਦੀ ਕਲਾ',
      te: 'విజయం మీదే',
      ta: 'வெற்றி நிச்சயம்',
      bn: 'সাফল্যের পথ',
      hinglish: 'Victory Awaits',
    },
    scenes: [
      SCENES.mot_climber,
      SCENES.af_serengeti,
      SCENES.lat_sunflower,
    ],
    sampleQuotes: {
      en: [
        'The only limit to our realization of tomorrow will be our doubts of today. Believe and conquer.',
      ],
      es: [
        'El único límite para nuestros logros de mañana serán nuestras dudas de hoy. ¡Cree en ti y triunfa!',
      ],
      pt: [
        'O sucesso é a soma de pequenos esforços repetidos dia após dia. Acredite no seu potencial!',
      ],
      ar: [
        'العزيمة والإصرار هما مفتاح كل نجاح عظيم. ثق بنفسك وواصل التقدم نحو أهدافك.',
      ],
      fr: [
        'Le succès n’est pas la clé du bonheur. Le bonheur est la clé du succès. Crois en tes rêves !',
      ],
      de: [
        'Der einzige Weg, großartige Arbeit zu leisten, ist zu lieben, was man tut. Geh deinen Weg!',
      ],
      hi: [
        'मंजिल उन्हीं को मिलती है जिनके सपनों में जान होती है, पंखों से कुछ नहीं होता हौसलों से उड़ान होती है।',
      ],
      mr: [
        'कठीण परिश्रम आणि स्वतःवरचा अतूट विश्वास यातूनच अशक्य गोष्टही शक्य होते. पुढे जात राहा!',
      ],
      gu: ['સખત પરિશ્રમ અને આત્મવિશ્વાસથી દરેક અસંભવ લક્ષ્ય શક્ય બને છે.'],
      pa: ['ਮਿਹਨਤ ਇੰਨੀ ਖਾਮੋਸ਼ੀ ਨਾਲ ਕਰੋ ਕਿ ਤੁਹਾਡੀ ਕਾਮਯਾਬੀ ਸ਼ੋਰ ਮਚਾ ਦੇਵੇ।'],
      te: ['కఠోర శ్రమ మరియు అచంచలమైన ఆత్మవిశ్వాసంతో ఏదైనా సాధించవచ్చు.'],
      ta: ['விடாமுயற்சியும் தன்னம்பிக்கையும் இருந்தால் எந்த இலக்கையும் அடையலாம்.'],
      bn: ['কঠোর পরিশ্রম এবং আত্মবিশ্বাসই সাফল্যের আসল চাবিকাঠি।'],
      ja: ['あなたの可能性は無限大です。今日も自信を持って前へ進みましょう。'],
      ko: ['당신의 열정이 곧 당신의 미래입니다. 오늘도 힘차게 전진하세요!'],
      zh: ['不忘初心，方得始终。相信自己，今天也将充满奇迹。'],
      hinglish: ['Mehnat itni khamoshi se karo ki tumhari kamyabi shor macha de.'],
    },
    recipientSuggestions: [
      { label: 'Champion', en: 'Champion', native: 'Campeón / कर्मवीर' },
      { label: 'Friend', en: 'My Friend', native: 'Friend / मित्र' },
    ],
  },
  spiritual: {
    id: 'spiritual',
    label: 'Spiritual Blessings',
    icon: '🕉️',
    category: 'mindset',
    defaultTitle: {
      en: 'Divine Blessings',
      es: 'Bendiciones Divinas',
      pt: 'Bênçãos Divinas',
      ar: 'بركات إلهية',
      tr: 'Hayırlı Dualar',
      ja: '心静かな祈り',
      ko: '평안한 기도',
      zh: '静心祈福',
      fr: 'Bénédictions',
      de: 'Göttlicher Segen',
      it: 'Benedizioni Divine',
      hi: 'जय श्री कृष्णा',
      mr: 'जय श्री कृष्ण',
      gu: 'જય શ્રી કૃષ્ણ',
      pa: 'ਸਤਿਨਾਮ ਵਾਹਿਗੁਰੂ',
      te: 'ఓం నమో నారాయణాయ',
      ta: 'ஓம் நமச்சிவாய',
      bn: 'জয় শ্রী কৃষ্ণ',
      hinglish: 'Jai Shree Krishna',
    },
    scenes: [
      SCENES.gm_krishna,
      SCENES.me_crescent,
      SCENES.fest_diyas,
    ],
    sampleQuotes: {
      en: ['May divine grace guide your steps, quiet your mind, and fill your spirit with boundless peace and strength.'],
      es: ['Que la paz y la gracia divina te acompañen siempre, iluminando tu camino y tu corazón.'],
      pt: ['Que as bênçãos divinas iluminem seus passos e tragam serenidade e paz ao seu coração.'],
      ar: ['نسأل الله أن يملأ قلبك بالسكينة والإيمان وأن يحفظك ويبارك في كل أيامك.'],
      hi: ['ईश्वर का स्मरण और मन में शांति ही जीवन का सबसे बड़ा धन है। आपका दिन मंगलमय हो।'],
      mr: ['ईश्वराचे नामस्मरण आणि मनात शांती हेच जीवनाचे खरे सुख आहे.'],
      gu: ['કર્મો કરતા રહો, ફળની ચિંતા ઈશ્વર પર છોડો. ભગવાનની કૃપા સદાય સાથે રહે.'],
      pa: ['ਵਾਹਿਗੁਰੂ ਸਭ ਦਾ ਭਲਾ ਕਰੇ। ਪਰਮਾਤਮਾ ਦੀ ਕਿਰਪਾ ਤੁਹਾਡੇ ਪਰਿਵਾਰ ਉੱਤੇ ਹਮੇਸ਼ਾ ਬਣੀ ਰਹੇ।'],
      te: ['భగవంతుని అనుగ్రహం మీపై సదా ఉండాలని ప్రార్థిస్తూ... మీ రోజు ప్రశాంతంగా గడవాలి.'],
      ta: ['இறைவனின் அருள் உங்கள் வாழ்வில் என்றென்றும் நிலைத்திருக்கட்டும்.'],
      bn: ['ঈশ্বরের স্মরণ ও মনের शांतिই জীবনের শ্রেষ্ঠ সম্পদ।'],
      ja: ['大自然の恵みと感謝の心が、あなたの心に静けさと安らぎをもたらしますように。'],
      ko: ['마음의 평화와 감사가 당신의 삶에 가득하기를 소망합니다.'],
      zh: ['愿智慧与宁静伴随您的左右，心灵丰盈，福泽绵长。'],
      hinglish: ['Bhagwan ki kripa aap par aur aapke parivaar par sadaiv bani rahe.'],
    },
    recipientSuggestions: [
      { label: 'Family', en: 'Family', native: 'Familia / परिवार' },
      { label: 'Elders', en: 'Respected Elders', native: 'Elders / बुजुर्ग' },
    ],
  },
  anniversary: {
    id: 'anniversary',
    label: 'Anniversary',
    icon: '💍',
    category: 'celebration',
    defaultTitle: {
      en: 'Happy Anniversary',
      es: '¡Feliz Aniversario!',
      pt: 'Feliz Aniversário de Casamento!',
      ar: 'ذكرى زواج سعيدة',
      tr: 'Yıldönümünüz Kutlu Olsun',
      fr: 'Joyeux Anniversaire de Mariage !',
      de: 'Alles Gute zum Hochzeitstag!',
      it: 'Buon Anniversario !',
      hi: 'विवाह वर्षगांठ की बधाई',
      mr: 'लग्नाच्या वाढदिवसाच्या हार्दिक शुभेच्छा',
      gu: 'લગ્ન વર્ષગાંઠની હાર્દિક શુભેચ્છાઓ',
      pa: 'ਵਿਆਹ ਦੀ ਵਰ੍ਹੇਗੰਢ ਮੁਬਾਰਕ',
      te: 'పెళ్లి రోజు శుభాకాంక్షలు',
      ta: 'திருமண நாள் நல்வாழ்த்துகள்',
      bn: 'বিবাহবার্ষিকীর শুভেচ্ছা',
      hinglish: 'Happy Anniversary',
    },
    scenes: [
      SCENES.lat_sunflower,
      SCENES.eu_paris,
    ],
    sampleQuotes: {
      en: ['Wishing a truly beautiful couple a lifetime of shared laughter, enduring love, and precious memories.'],
      es: ['¡Deseando a una hermosa pareja toda una vida de amor, risas compartidas y felicidad eterna!'],
      pt: ['Que o amor e a cumplicidade de vocês continuem crescendo a cada novo ano. Parabéns!'],
      ar: ['أطيب التهاني بمناسبة ذكرى زواجكما السعيدة، دامت أيامكما مليئة بالمحبة والوفاء.'],
      fr: ['Joyeux Anniversaire de Mariage ! Que votre amour continue de grandir et de rayonner chaque jour.'],
      hi: ['आप दोनों की जोड़ी सदा सलामत रहे, प्यार और विश्वास का यह बंधन युगों-युगों तक महकता रहे।'],
      mr: ['तुमची ही जोडी अशीच आनंदी आणि सुखसमाधानाची राहो. लग्नाच्या वाढदिवसाच्या मनःपूर्वक शुभेच्छा!'],
      gu: ['તમારા બંનેની જોડી સદાય હસતી-રમતી રહે અને પ્રેમનો આ સંબંધ અખૂટ રહે. લગ્ન વર્ષગાંઠ મુબારક!'],
      pa: ['ਤੁਹਾਡੀ ਜੋੜੀ ਹਮੇਸ਼ਾ ਖੁਸ਼ਹਾਲ ਅਤੇ ਸਲਾਮਤ ਰਹੇ। ਵਰ੍ਹੇਗੰਢ ਦੀਆਂ ਬਹੁਤ ਬਹੁਤ ਵਧਾਈਆਂ!'],
      te: ['మీ దాంపత్య జీవితం కలకాలం సుఖసంతోషాలతో సాగాలని కోరుకుంటూ... పెళ్లి రోజు శుభాకాంక్షలు!'],
      ta: ['உங்கள் அன்பு என்றும் நிலைத்திருக்க இனிய திருமண நாள் நல்வாழ்த்துகள்!'],
      bn: ['আপনাদের ভালোবাসার বন্ধন অটুট থাকুক। শুভ বিবাহবার্ষিকী!'],
      hinglish: ['Aap dono ki jodi hamesha aisi hi khushhaal aur salamat rahe. Happy Anniversary!'],
    },
    recipientSuggestions: [
      { label: 'Couple', en: 'Beautiful Couple', native: 'Pareja / जोड़ी' },
      { label: 'Mom & Dad', en: 'Dearest Mom & Dad', native: 'Parents / माता-पिता' },
    ],
  },
  thank_you: {
    id: 'thank_you',
    label: 'Gratitude & Thanks',
    icon: '🙏',
    category: 'celebration',
    defaultTitle: {
      en: 'Thank You',
      es: '¡Muchas Gracias!',
      pt: 'Muito Obrigado!',
      ar: 'شكراً جزيلاً',
      tr: 'Çok Teşekkürler',
      ja: '心より感謝いたします',
      ko: '진심으로 감사드립니다',
      zh: '衷心感谢',
      fr: 'Merci Beaucoup !',
      de: 'Herzlichen Dank!',
      it: 'Grazie di Cuore !',
      sw: 'Asante Sana',
      hi: 'हार्दिक आभार',
      mr: 'मनःपूर्वक आभार',
      gu: 'ખૂબ ખૂબ આભાર',
      pa: 'ਦਿਲੋਂ ਧੰਨਵਾਦ',
      te: 'హృదయపూర్వక కృతజ్ఞతలు',
      ta: 'மனமார்ந்த நன்றிகள்',
      bn: 'আন্তরিক ধন্যবাদ',
      hinglish: 'Dil Se Dhanyawaad',
    },
    scenes: [
      SCENES.eu_paris,
      SCENES.lat_sunflower,
    ],
    sampleQuotes: {
      en: ['Thank you from the bottom of my heart for your kindness, support, and warm presence.'],
      es: ['¡Muchas gracias de todo corazón por tu amabilidad, apoyo y calidez siempre!'],
      pt: ['Agradeço de todo coração por sua bondade, carinho e constante apoio.'],
      ar: ['شكراً من أعماق قلبي على لطفك ودعمك ووجودك الطيب دائماً.'],
      fr: ['Un grand merci du fond du cœur pour votre gentillesse, votre soutien et votre bienveillance.'],
      de: ['Von ganzem Herzen danke ich dir für deine Unterstützung, Herzlichkeit und Hilfsbereitschaft.'],
      hi: ['आपके अमूल्य स्नेह, सहयोग और शुभकामनाओं के लिए हृदय की गहराइयों से बहुत-बहुत धन्यवाद एवं आभार।'],
      mr: ['आपल्या बहुमूल्य प्रेम आणि सहकार्याबद्दल मनापासून खूप खूप धन्यवाद आणि आभार.'],
      gu: ['તમારા પ્રેમ અને સહકાર માટે હૃદયપૂર્વક ખૂબ ખૂબ આભાર.'],
      pa: ['ਤੁਹਾਡੇ ਪਿਆਰ ਅਤੇ ਸਹਿਯੋਗ ਲਈ ਦਿਲੋਂ ਬਹੁਤ ਬਹੁਤ ਧੰਨਵਾਦ।'],
      te: ['మీ ఆప్యాయత మరియు సహాయానికి హృదయపూర్వక ధన్యవాదాలు.'],
      ta: ['உங்கள் அன்பிற்கும் ஆதரவிற்கும் என் மனமார்ந்த நன்றிகள்.'],
      bn: ['আপনার ভালোবাসা এবং সমর্থনের জন্য আন্তরিক ধন্যবাদ ও কৃতজ্ঞতা।'],
      ja: ['温かいお心遣いとご支援に、心より深く感謝申し上げます。'],
      ko: ['베풀어주신 따뜻한 배려와 사랑에 깊이 감사드립니다.'],
      zh: ['由衷感谢您的关怀与支持，铭记于心，感激不尽。'],
      hinglish: ['Aapke pyaar aur support ke liye dil se dhanyawaad. Always grateful!'],
    },
    recipientSuggestions: [
      { label: 'Everyone', en: 'Dear One', native: 'Dear Friend / आदरणीय' },
    ],
  },
  festival: {
    id: 'festival',
    label: 'Festival Wishes',
    icon: '🎉',
    category: 'festival',
    defaultTitle: {
      en: 'Festive Greetings',
      es: '¡Felices Fiestas!',
      pt: 'Boas Festas!',
      ar: 'أجمل التهاني والتبريكات',
      fr: 'Joyeuses Fêtes !',
      de: 'Frohe Festtage!',
      it: 'Buone Feste !',
      hi: 'त्योहार की शुभकामनाएं',
      mr: 'सणाच्या हार्दिक शुभेच्छा',
      gu: 'તહેવારની શુભકામનાઓ',
      pa: 'ਤਿਉਹਾਰ ਦੀਆਂ ਵਧਾਈਆਂ',
      te: 'పండుగ శుభాకాంక్షలు',
      ta: 'பண்டிகை நல்வாழ்த்துகள்',
      bn: 'উৎসবের শুভেচ্ছা',
      hinglish: 'Tyohar ki Badhai',
    },
    scenes: [
      SCENES.fest_diyas,
      SCENES.me_crescent,
    ],
    sampleQuotes: {
      en: ['May this joyous celebration bring peace, unity, prosperity, and endless smiles to your home.'],
      es: ['¡Que esta hermosa fiesta traiga paz, unión y prosperidad a tu hogar!'],
      pt: ['Desejo que esta celebração traga muita harmonia, saúde e momentos inesquecíveis para sua família.'],
      ar: ['كل عام وأنتم بخير، ونسأل الله أن يديم عليكم الأفراح والمسرات.'],
      fr: ['Que ces moments de fête vous apportent joie, sérénité et bonheur partagé en famille.'],
      hi: ['त्योहारों की यह मिठास और खुशियां आपके जीवन में हमेशा बनी रहें। आप सभी को हार्दिक बधाई!'],
      mr: ['सणांचा हा गोडवा आपल्या आयुष्यात कायम राहो. आपणा सर्वांना मनःपूर्वक शुभेच्छा!'],
      gu: ['આ પાવન પર્વ તમારા ઘરમાં અપાર સુખ-સમૃદ્ધિ લાવે.'],
      pa: ['ਇਹ ਖੁਸ਼ੀਆਂ ਭਰਿਆ ਤਿਉਹਾਰ ਤੁਹਾਡੇ ਲਈ ਤਰੱਕੀ ਲੈ ਕੇ ਆਵੇ।'],
      te: ['ఈ పండుగ మీ ఇంట ఆనందాలను నింపాలని కోరుకుంటూ... పండుగ శుభాకాంక్షలు!'],
      ta: ['இந்த நன்னாளில் உங்கள் இல்லத்தில் இன்பமும் செழிப்பும் பொங்கட்டும்.'],
      bn: ['এই উৎসবের মিষ্টি আনন্দ আপনার জীবনে চিরকাল থাকুক।'],
      hinglish: ['Is khoobsurat parv par aapko aur aapke apno ko dher saara pyaar aur shubhkaamnayein.'],
    },
    recipientSuggestions: [
      { label: 'Everyone', en: 'Everyone', native: 'All / सभी प्रियजन' },
    ],
  },
  custom: {
    id: 'custom',
    label: 'Custom Card',
    icon: '✨',
    category: 'celebration',
    defaultTitle: {
      en: 'Warm Wishes',
      es: 'Mis Mejores Deseos',
      pt: 'Com Carinho',
      ar: 'أطيب التمنيات',
      fr: 'Meilleurs Vœux',
      de: 'Beste Wünsche',
      it: 'I Miei Migliori Auguri',
      hi: 'हार्दिक शुभकामनाएं',
      mr: 'सस्नेह नमस्कार',
      gu: 'શુભેચ્છાઓ',
      pa: 'ਸ਼ੁਭਕਾਮਨਾਵਾਂ',
      te: 'హృదయపూర్వక శుభాకాంక్షలు',
      ta: 'நல்வாழ்த்துகள்',
      bn: 'শুভকামনা',
      hinglish: 'Warm Wishes',
    },
    scenes: [
      SCENES.gm_sunrise,
      SCENES.bday_cake,
      SCENES.mot_climber,
    ],
    sampleQuotes: {
      en: ['Wishing you joy, good health, peace of mind, and all the best things in life.'],
      es: ['¡Deseándote alegría, salud, paz mental y todo lo mejor en la vida!'],
      pt: ['Desejando a você muita alegria, saúde, paz de espírito e tudo de melhor na vida.'],
      ar: ['أتمنى لك أياماً عامرة بالفرح وراحة البال والتوفيق الدائم.'],
      fr: ['En vous souhaitant joie, santé, paix et tout le meilleur pour l’avenir.'],
      hi: ['आपके जीवन में सदा सुख, शांति, प्रेम और खुशहाली बनी रहे।'],
      mr: ['आपल्या आयुष्यात सदा सुख, शांती, समाधान आणि भरभराट राहो.'],
      gu: ['તમારા જીવનમાં સદાય સુખ, શાંતિ અને સમૃદ્ધિ રહે.'],
      pa: ['ਤੁਹਾਡੀ ਜ਼ਿੰਦਗੀ ਵਿੱਚ ਹਮੇਸ਼ਾ ਖੁਸ਼ੀਆਂ ਅਤੇ ਸ਼ਾਂਤੀ ਬਣੀ ਰਹੇ।'],
      te: ['మీ జీవితంలో ఎల్లప్పుడూ ఆనందం, శాంతి నిండాలని ఆకాంక్షిస్తున్నాము.'],
      ta: ['உங்கள் வாழ்வில் எப்போதும் மகிழ்ச்சியும் அமைதியும் நிலவட்டும்.'],
      bn: ['আপনার জীবনে সদা सुख ও শান্তি বিরাজ করুক।'],
      hinglish: ['Wishing you happiness, peace and success always.'],
    },
    recipientSuggestions: [
      { label: 'Dear One', en: 'Dear One', native: 'Dear Friend / प्रिय' },
    ],
  },
};
